config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :transactions
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  

  match '/purchase', :to => 'transactions#new'
  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new
    @title = "New Transaction"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = current_user.transactions.build(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Item Purchased' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Description of purchase' %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label 'Account name (Discover Card, Master Card ETC)' %><br />
    <%= f.text_field :accounttype %>
  </div>
  <div class="field">
    <%= f.label 'How much did you spend? (Integers Only)' %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit "Create"%>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<tr>
  <td class="transaction">
    <span class="content"><b>Transaction Name: </b><%= transaction.name %></span><br/>
    <span class="content"><b>Description: </b><%= transaction.description %></span><br/>
    <span class="content"><b>Account: </b><%= transaction.accounttype %></span><br/>
    <span class="content"><b>Amount: $</b><%= transaction.amount %></span><br/><br/>
    <span class="timestamp">
      Posted <%= time_ago_in_words(transaction.created_at) %> ago.
    </span>
  </td>
  <% user = transaction.user rescue User.find(transaction.user_id) %>
  <% if current_user?(user) %>
    <td>
      <%= link_to "delete", transaction, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => transaction.name %>
    </td>
  <% end %>
</tr>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th>Accounttype</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.id %></td>
    <td><%= transaction.name %></td>
    <td><%= transaction.description %></td>
    <td><%= transaction.user_id %></td>
    <td><%= transaction.accounttype %></td>
    <td><%= transaction.amount %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @transaction.id %>
</p>

<p>
  <b>Name:</b>
  <%= @transaction.name %>
</p>

<p>
  <b>Description:</b>
  <%= @transaction.description %>
</p>

<p>
  <b>User:</b>
  <%= @transaction.user_id %>
</p>

<p>
  <b>Accounttype:</b>
  <%= @transaction.accounttype %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>